#import "../../typst-ko/lib.typ": *

= Appendix B --- Diagnostics index

Only the diagnostics that this book's examples actually trigger are listed. A code keeps its meaning across releases; the compiler explains the details and the repair at the site.

== At translation time

#dtable(
  columns: 3,
  id: "a2-static",
  caption: [Diagnostics shown by the examples],
  [*Code*], [*Meaning*], [*Shown in*],
  [`E-ACCESS-MODE`], [the body breaks the read or write promise made with `access`], [#chref("parallel-atomic")],
  [`E-ALLOC-AMBIGUOUS`], [more than one fitting allocator and none chosen with `using`], [#chref("fixed-memory")],
  [`E-ALLOC-NESTED`], [allocated from an outer source while an inner region of the same root is open], [#chref("regions")],
  [`E-ALLOC-NOCAP`], [declares `alloc` but receives no allocation capability], [#chref("capabilities")],
  [`E-ALLOC-NOSOURCE`], [a call draws from an allocator but no fitting one is visible in this op], [#chref("fixed-memory")],
  [`E-ALLOC-OUTLIVES`], [region bytes handed to an actor born outside the region], [#chref("regions")],
  [`E-ALLOC-SHARED`], [an allocator whose cursor is not atomic is handed to a task], [#chref("tasks-channels")],
  [`E-ALLOC-TASK`], [an op that carves from a root is spawned as a task], [#chref("tasks-channels")],
  [`E-ALLOC-USING-UNUSED`], [`using` on a call that does not draw from an allocator], [#chref("fixed-memory"), #chref("lib-containers")],
  [`E-ASM-TARGET-UNKNOWN`], [the machine name in an `asm` clause is not a known target], [#chref("hardware")],
  [`E-ASM-UNBOUND`], [the assembly template names an undeclared operand], [#chref("hardware")],
  [`E-ATOMIC-NOCAP`], [declares `atomic` but receives no `cap atomic`], [#chref("parallel-atomic")],
  [`E-ATOMIC-ORDER`], [a memory ordering that has no meaning for that atomic operation], [#chref("parallel-atomic")],
  [`E-BLOCK-UNCLOSED`], [a block opened with `do` is never closed with `end`], [#chref("first-program")],
  [`E-BOUND-UNSAT`], [the type argument does not satisfy the required trait], [#chref("generics"), #chref("traits")],
  [`E-BRAND-REUSED`], [a brand opens a second storage], [#chref("lib-alloc")],
  [`E-CAP-FORGE`], [spawns an actor holding a capability without holding that capability], [#chref("fixed-memory"), #chref("actors")],
  [`E-CAP-KIND`], [a capability of the wrong kind was handed over], [#chref("capabilities")],
  [`E-CAP-MISSING`], [a capability-requiring builtin was not given its capability as the first operand], [#chref("capabilities")],
  [`E-CHAR`], [a character (symbol) this language does not have], [#chref("locals"), #chref("control"), #chref("expr"), #chref("slices")],
  [`E-CHAR-WIDTH`], [a character literal is not a single character], [#chref("surface")],
  [`E-CLAUSE-ORDER`], [the clauses of an op header are out of the fixed order], [#chref("first-program"), #chref("surface"), #chref("generics")],
  [`E-COMPTIME-ARG`], [a run-time value in a `comptime` position], [#chref("generics")],
  [`E-CONC-ALONE`], [a task group spawns one task that waits for a peer], [#chref("tasks-channels")],
  [`E-CONC-DEADLOCK`], [every task in the group receives and none sends], [#chref("tasks-channels")],
  [`E-CONFIG-TYPE`], [the configuration gives a value the option does not offer], [#chref("build-test")],
  [`E-CONFIG-UNDEF`], [a configuration or `config` names an undeclared build option], [#chref("build-test")],
  [`E-CONTRACT-DEAD`], [declares an error that `requires` already excludes], [#chref("contracts")],
  [`E-CONTRACT-IMPOSSIBLE`], [a call with constant arguments breaks the callee's `requires`], [#chref("contracts"), #chref("lib-alloc")],
  [`E-DEP-MISSING`], [the file at a `use … from` place cannot be read], [#chref("modules")],
  [`E-EFFECT`], [performs an effect its `effects` clause does not declare], [#chref("effects"), #chref("fixed-memory"), #chref("tasks-channels")],
  [`E-EFFECT-CALC`], [a pure `fn` performs an effect], [#chref("intro"), #chref("ops"), #chref("effects"), #chref("capabilities"), #chref("regions"), #chref("pipe")],
  [`E-EFFECT-DUP`], [the same atom twice in an `effects` clause], [#chref("effects"), #chref("proofs-effects")],
  [`E-EFFECT-NO-CAP`], [declares `io` (or similar) without a capability that authorises it], [#chref("first-program"), #chref("capabilities")],
  [`E-EFFECT-NONE-MIX`], [`none` written together with a real effect], [#chref("effects")],
  [`E-EFFECT-PURITY`], [a `fn` writes state visible to its caller or actor], [#chref("ops"), #chref("effects"), #chref("actors")],
  [`E-EFFECT-REDUNDANT`], [`effects none` written on a `fn`], [#chref("ops")],
  [`E-EFFECT-UNDEF`], [an effect word outside the closed vocabulary], [#chref("effects"), #chref("proofs-effects")],
  [`E-ENS-UNDEF`], [`ensures` names something undefined --- the returned value is `ret`], [#chref("contracts")],
  [`E-ENTRY-PARAMS`], [the entry point takes a non-capability input], [#chref("capabilities")],
  [`E-ENUM-DOT`], [an enum variant not closed with `.`], [#chref("structs-enums")],
  [`E-ENUM-INFINITE`], [a variant embeds its own type by value], [#chref("structs-enums")],
  [`E-ERR-UNDECLARED`], [returns an error not in its `errors` clause], [#chref("option-result")],
  [`E-ESCAPE`], [a reference to a local escapes the op], [#chref("references")],
  [`E-EXCL`], [overlapping borrows or owner access to the same value], [#chref("references"), #chref("tasks-channels"), #chref("proofs-loops")],
  [`E-EXPR-APP`], [a call inside an `expr` island is not parenthesised], [#chref("expr")],
  [`E-EXPR-CHAIN`], [comparisons chained in an `expr` island], [#chref("surface")],
  [`E-EXPR-UNARY`], [a unary operator in an `expr` island], [#chref("expr")],
  [`E-FFI-NOCAP`], [calls C without receiving `cap c`], [#chref("ffi")],
  [`E-FFI-NOEFFECT`], [an op calling C declares no effect], [#chref("ffi")],
  [`E-FFI-NOUNSAFE`], [calls C without the `unsafe` mark], [#chref("ffi")],
  [`E-FFI-TYPE`], [a type the C ABI cannot express crosses the boundary], [#chref("ffi")],
  [`E-FIELD-GLUED`], [tried to read a field by gluing a dot to a value --- write `field`], [#chref("surface")],
  [`E-FN-CAP`], [an op to be passed as a callback requires a capability], [#chref("ffi")],
  [`E-FN-NOTEXPORT`], [`unsafe_fn` names an op that is not `export extern`], [#chref("ffi")],
  [`E-FOLD-OP`], [a `pipe` stage names an op that does not exist], [#chref("pipe")],
  [`E-GROUP-UNCLOSED`], [an unclosed parenthesis], [#chref("surface")],
  [`E-GUARD-FALLTHROUGH`], [the `else` of a `guard` does not leave], [#chref("control")],
  [`E-HEAP-NOHOST`], [asks for the growing root on a freestanding target], [#chref("regions")],
  [`E-IF-VALUE`], [`if` used as a value], [#chref("locals")],
  [`E-IMMUTABLE`], [`set` on a name bound with `let`], [#chref("locals")],
  [`E-IR-ARITY`], [an op is called with the wrong number of arguments], [#chref("ops"), #chref("proofs-syntax")],
  [`E-IR-UNDEF`], [a name unknown at that place], [#chref("locals"), #chref("control"), #chref("modules"), #chref("generics"), #chref("actors")],
  [`E-ISR-CALLED`], [an interrupt handler called from code], [#chref("hardware")],
  [`E-ISR-EFFECT`], [an interrupt handler does not declare `effects device`], [#chref("hardware")],
  [`E-ISR-PARAMS`], [an interrupt handler takes parameters], [#chref("hardware")],
  [`E-LET-NOVALUE`], [nothing after `be`], [#chref("locals")],
  [`E-LOCK-NOTYET`], [shared lock types are not built yet], [#chref("tasks-channels")],
  [`E-MATCH-INEXHAUSTIVE`], [a `match` does not cover every case], [#chref("control"), #chref("structs-enums"), #chref("option-result")],
  [`E-MATCH-REDUNDANT`], [a `match` arm can never run (an arm after `_`, overlapping ranges)], [#chref("option-result")],
  [`E-METHOD-UNDEF`], [no op of that name is attached to the receiver's type], [#chref("generics"), #chref("traits")],
  [`E-MMIO-BYVALUE`], [an mmio register block taken by value], [#chref("hardware")],
  [`E-MMIO-PERM`], [writes a read-only register], [#chref("hardware")],
  [`E-MREF-SLICE`], [`mut ref slice` used], [#chref("references")],
  [`E-NAME-BUILTIN`], [a builtin op's name is used for a declaration or local], [#chref("ops"), #chref("locals")],
  [`E-NAME-DUP`], [the same name declared twice in one module], [#chref("modules")],
  [`E-NAME-SHADOW`], [re-binds a live name (shadowing)], [#chref("surface"), #chref("locals")],
  [`E-OPT-UNUSED`], [a declared build option that no code reads], [#chref("build-test")],
  [`E-OWN-INCOMPLETE`], [a value that needs completion is dropped implicitly], [#chref("ownership"), #chref("io-files"), #chref("lib-io-net")],
  [`E-OWN-JOIN`], [ownership state differs between branches], [#chref("ownership")],
  [`E-OWN-MOVED`], [uses a value after it was moved], [#chref("ownership"), #chref("actors"), #chref("io-files"), #chref("lib-alloc"), #chref("lib-io-net")],
  [`E-PAR-ASSOC`], [the reduction operator is not associative], [#chref("parallel-atomic")],
  [`E-PAR-CARRY`], [a split loop writes a local that lives across iterations], [#chref("parallel-atomic")],
  [`E-PAR-FLOAT`], [a floating-point accumulation declared splittable], [#chref("parallel-atomic")],
  [`E-PAR-NOLOOP`], [the `parallel` clause finds no loop to split], [#chref("parallel-atomic")],
  [`E-PAR-READ`], [a split loop reads another iteration's element], [#chref("parallel-atomic")],
  [`E-PAR-WRITE`], [a split loop writes another iteration's element], [#chref("parallel-atomic"), #chref("proofs-races")],
  [`E-PIPE-NO-TERMINAL`], [a stage after the terminal], [#chref("pipe")],
  [`E-PIPE-STAGE`], [a word that is not a `pipe` stage], [#chref("pipe")],
  [`E-PROFILE-LEVEL`], [uses concurrency the build profile does not provide], [#chref("actors")],
  [`E-REGION-ESCAPE`], [carries region bytes out of the region], [#chref("regions")],
  [`E-RETURN-PARTIAL`], [some path does not return a value], [#chref("surface"), #chref("ops"), #chref("control")],
  [`E-SPAWN-SCOPE`], [spawns a task outside a `task_group`], [#chref("tasks-channels")],
  [`E-TIER-EFFECT`], [an effect the declared machine tier cannot carry], [#chref("hardware")],
  [`E-TOPLEVEL`], [something that cannot appear at top level is at top level], [#chref("surface")],
  [`E-TRAIT-EFFECT`], [the implementing op has more effects than the signature], [#chref("traits")],
  [`E-TRAIT-MISSING`], [an op required by the trait is missing], [#chref("traits")],
  [`E-TRAIT-SIG`], [`fn`/`proc` in a signature, or a parameter-count mismatch], [#chref("traits")],
  [`E-TYPE-ARRAY`], [`array` length written after the type], [#chref("slices")],
  [`E-TYPE-BITCAST`], [`bit_cast` target is not a plain scalar], [#chref("fixed-memory")],
  [`E-TYPE-COND`], [a non-boolean in a condition], [#chref("numbers")],
  [`E-TYPE-DECL`], [`be` in a type declaration], [#chref("named-types")],
  [`E-TYPE-FIELD`], [a field is missing or unknown when building a struct], [#chref("structs-enums")],
  [`E-TYPE-INSTANCE`], [mixes different instances of the same generic], [#chref("lib-alloc")],
  [`E-TYPE-KIND`], [a type of the wrong kind for that operation (e.g. `cast` of `bool`)], [#chref("named-types")],
  [`E-TYPE-LOGICAL`], [a non-boolean value given to a logical operation], [#chref("expr")],
  [`E-TYPE-MUT`], [writes an element of a non-`mut` slice], [#chref("slices")],
  [`E-TYPE-NOMINAL`], [mixes nominally distinct types], [#chref("named-types")],
  [`E-TYPE-REF`], [writes through a shared `ref`], [#chref("references")],
  [`E-TYPE-RETURN`], [the returned value does not match the op's output type], [#chref("option-result"), #chref("build-test")],
  [`E-TYPE-SIGN`], [mixes signs with no value-preserving widening], [#chref("numbers"), #chref("proofs-math"), #chref("proofs-numbers")],
  [`E-TYPE-WIDTH`], [the value does not fit the declared type], [#chref("surface"), #chref("named-types")],
  [`E-UNSAFE-UNDECLARED`], [declares the `unsafe` effect but the op is not marked `unsafe`], [#chref("ffi")],
  [`E-VISIBILITY`], [reaches a non-exported name of another module], [#chref("modules")],
  [`E-VOCAB-REMOVED`], [a removed word or spelling], [#chref("surface"), #chref("ops"), #chref("control"), #chref("effects"), #chref("proofs-syntax")],
  [`E-WIDEN-SIGN`], [`widen` from a signed to an unsigned type], [#chref("named-types")],
  [`W-EFFECT-OVER`], [an effect declared but never performed (warning)], [#chref("effects"), #chref("capabilities")],
  [`W-NOT-YET`], [a word accepted by name that has no meaning yet], [#chref("named-types")],
  [`W-USE-EXTERNAL`], [imports a module not in the compilation unit (warning)], [#chref("lib-map")],
)

== When execution stops

#dtable(
  columns: 3,
  id: "a2-runtime",
  caption: [Run-time diagnostics],
  [*Code*], [*Meaning*], [*Shown in*],
  [`E-VM-OVERFLOW`], [integer overflow at the declared width], [#chref("numbers")],
  [`E-VM-DIV0`], [division by zero], [#chref("numbers")],
  [`E-VM-CAST`], [a narrowing or `cast` value does not fit], [#chref("numbers")],
  [`E-VM-SHIFT`], [shift amount not smaller than the width], [#chref("numbers")],
  [`E-VM-BOUNDS`], [index out of bounds], [#chref("slices")],
  [`E-VM-NONE`], [took the value out of `none`], [#chref("option-result")],
  [`E-VM-CONTRACT`], [a contract was broken], [#chref("contracts")],
  [`E-VM-PANIC`], [the program called `panic`], [#chref("control")],
  [`E-VM-ANALYSIS`], [an eliminated check was actually needed (compiler bug)], [#chref("proofs-numbers")],
  [`E-TEST-FAIL`], [an `expect` in a test is false], [#chref("build-test")],
)
