#import "../lib.typ": *

= 부록 B --- 진단 찾아보기

이 책의 예제가 실제로 일으킨 진단만 모았다. 코드는 판이 바뀌어도 같은 뜻을 지킨다. 진단의 긴 영문 설명과 고치는 법은 컴파일러가 그 자리에서 말한다.

== 번역할 때

#dtable(
  columns: 3,
  id: "a2-static",
  caption: [예제가 보이는 진단],
  [*코드*], [*뜻*], [*보이는 곳*],
  [`E-ALLOC-NESTED`], [같은 뿌리의 안쪽 영역이 열린 채 바깥 출처로 깎았다], [#chref("regions")],
  [`E-ALLOC-NOCAP`], [`alloc` 을 적었는데 할당 권한을 받지 않았다], [#chref("capabilities")],
  [`E-ASM-UNBOUND`], [어셈블리 템플릿이 선언하지 않은 피연산자를 부른다], [#chref("hardware")],
  [`E-ATOMIC-NOCAP`], [`atomic` 을 적었는데 `cap atomic` 을 받지 않았다], [#chref("parallel-atomic")],
  [`E-ATOMIC-ORDER`], [그 원자 연산에 뜻이 없는 기억 차례다], [#chref("parallel-atomic")],
  [`E-BOUND-UNSAT`], [타입 인자가 요구한 트레이트를 갖추지 못했다], [#chref("generics")],
  [`E-CAP-FORGE`], [권한 칸을 가진 액터를 그 권한 없이 띄운다], [#chref("fixed-memory")],
  [`E-CAP-KIND`], [다른 종류의 권한을 건넸다], [#chref("capabilities")],
  [`E-CAP-MISSING`], [권한이 필요한 내장 연산에 권한을 첫 피연산자로 적지 않았다], [#chref("capabilities")],
  [`E-CLAUSE-ORDER`], [op 머리의 절이 정해진 차례를 어겼다], [#chref("first-program")],
  [`E-COMPTIME-ARG`], [`comptime` 자리에 실행 값을 주었다], [#chref("generics")],
  [`E-CONC-ALONE`], [묶음이 흐름 하나만 만들고 그 흐름이 짝을 기다린다], [#chref("tasks-channels")],
  [`E-CONC-DEADLOCK`], [묶인 흐름이 모두 받기만 하고 아무도 보내지 않는다], [#chref("tasks-channels")],
  [`E-CONTRACT-DEAD`], [`requires` 가 이미 배제한 오류를 선언했다], [#chref("contracts")],
  [`E-CONTRACT-IMPOSSIBLE`], [상수끼리의 호출이 상대의 `requires` 를 어긴다], [#chref("contracts"), #chref("lib-alloc")],
  [`E-EFFECT`], [선언하지 않은 효과를 낸다], [#chref("effects"), #chref("tasks-channels")],
  [`E-EFFECT-CALC`], [순수한 `fn` 이 효과를 낸다], [#chref("intro"), #chref("ops")],
  [`E-EFFECT-DUP`], [효과 줄에 같은 원자를 두 번 적었다], [#chref("effects")],
  [`E-EFFECT-NO-CAP`], [`io` 따위를 적었는데 허락하는 권한이 없다], [#chref("capabilities")],
  [`E-EFFECT-NONE-MIX`], [`none` 을 다른 효과와 함께 적었다], [#chref("effects")],
  [`E-EFFECT-PURITY`], [`fn` 이 호출자나 액터가 볼 수 있는 상태에 쓴다], [#chref("ops"), #chref("actors")],
  [`E-EFFECT-REDUNDANT`], [`fn` 에 `effects none` 을 적었다], [#chref("ops")],
  [`E-EFFECT-UNDEF`], [목록에 없는 효과 낱말이다], [#chref("effects")],
  [`E-ENTRY-PARAMS`], [시작점이 권한 아닌 입력을 받는다], [#chref("capabilities")],
  [`E-ENUM-DOT`], [열거의 갈래를 마침표로 닫지 않았다], [#chref("structs-enums")],
  [`E-ENUM-INFINITE`], [갈래가 자기 타입을 값으로 품는다], [#chref("structs-enums")],
  [`E-ERR-UNDECLARED`], [`errors` 절에 없는 오류를 돌려준다], [#chref("option-result")],
  [`E-ESCAPE`], [지역을 가리키는 참조가 op 밖으로 나간다], [#chref("references")],
  [`E-EXCL`], [같은 값에 대한 빌림이 겹친다], [#chref("references"), #chref("proofs-ownership")],
  [`E-EXPR-APP`], [`expr` 섬 안의 부름을 괄호로 묶지 않았다], [#chref("expr")],
  [`E-EXPR-CHAIN`], [`expr` 섬에서 비교를 이어 썼다], [#chref("surface")],
  [`E-EXPR-UNARY`], [`expr` 섬에 단항 연산자를 썼다], [#chref("expr")],
  [`E-FFI-NOCAP`], [C 를 부르는데 `cap c` 를 받지 않았다], [#chref("ffi")],
  [`E-FFI-NOUNSAFE`], [C 를 부르는데 `unsafe` 표시가 없다], [#chref("ffi")],
  [`E-FFI-TYPE`], [C ABI 가 표현할 수 없는 타입이 경계를 건넌다], [#chref("ffi")],
  [`E-GROUP-UNCLOSED`], [괄호가 닫히지 않았다], [#chref("surface")],
  [`E-GUARD-FALLTHROUGH`], [`guard` 의 `else` 가 떠나지 않는다], [#chref("control")],
  [`E-HEAP-NOHOST`], [운영체제 없는 대상에서 자라는 뿌리를 청한다], [#chref("regions")],
  [`E-IF-VALUE`], [`if` 를 값으로 썼다], [#chref("locals")],
  [`E-IMMUTABLE`], [`let` 으로 지은 이름에 `set` 했다], [#chref("locals")],
  [`E-ISR-CALLED`], [인터럽트 처리기를 코드에서 불렀다], [#chref("hardware")],
  [`E-LET-NOVALUE`], [`be` 뒤에 값이 없다], [#chref("locals")],
  [`E-MATCH-INEXHAUSTIVE`], [`match` 가 모든 경우를 덮지 않는다], [#chref("control"), #chref("structs-enums")],
  [`E-METHOD-UNDEF`], [수신자의 타입에 그 이름의 붙은 op 이 없다], [#chref("traits")],
  [`E-MMIO-BYVALUE`], [레지스터 묶음을 값으로 받는다], [#chref("hardware")],
  [`E-MMIO-PERM`], [읽기 전용 레지스터에 쓴다], [#chref("hardware")],
  [`E-MREF-SLICE`], [`mut ref slice` 를 썼다], [#chref("references")],
  [`E-NAME-DUP`], [한 모듈에 같은 이름을 두 번 선언했다], [#chref("modules")],
  [`E-NAME-SHADOW`], [살아 있는 이름을 다시 지었다(가림)], [#chref("surface"), #chref("locals")],
  [`E-OPT-UNUSED`], [선언한 빌드 손잡이를 아무 코드도 읽지 않는다], [#chref("build-test")],
  [`E-OWN-INCOMPLETE`], [완결이 필요한 값을 끝내지 않고 버린다], [#chref("ownership"), #chref("io-files"), #chref("lib-io-net")],
  [`E-OWN-JOIN`], [갈래마다 소유 상태가 다르다], [#chref("ownership")],
  [`E-OWN-MOVED`], [옮긴 값을 다시 쓴다], [#chref("ownership"), #chref("actors"), #chref("lib-alloc")],
  [`E-PAR-ASSOC`], [모으는 연산이 결합적이지 않다], [#chref("parallel-atomic")],
  [`E-PAR-CARRY`], [나누는 되풀이가 걸음을 넘어 사는 자리에 쓴다], [#chref("parallel-atomic")],
  [`E-PAR-READ`], [나누는 되풀이가 남의 원소를 읽는다], [#chref("parallel-atomic")],
  [`E-PIPE-NO-TERMINAL`], [종결자 뒤에 스테이지가 온다], [#chref("pipe")],
  [`E-PIPE-STAGE`], [`pipe` 스테이지 목록에 없는 낱말이다], [#chref("pipe")],
  [`E-PROFILE-LEVEL`], [빌드 프로파일이 주지 않는 동시성을 쓴다], [#chref("actors")],
  [`E-REGION-ESCAPE`], [영역에서 얻은 바이트를 밖으로 들고 나간다], [#chref("regions")],
  [`E-REGION-KIND`], [영역의 종류가 닫힌 여덟에 없다], [#chref("regions")],
  [`E-RETURN-PARTIAL`], [어떤 길에서 값을 돌려주지 않는다], [#chref("control")],
  [`E-SPAWN-SCOPE`], [`task_group` 밖에서 흐름을 만든다], [#chref("tasks-channels")],
  [`E-TIER-EFFECT`], [선언한 기계 등급이 감당하지 못하는 효과다], [#chref("hardware")],
  [`E-TRAIT-EFFECT`], [갖춘 op 이 서명보다 많은 효과를 가진다], [#chref("traits")],
  [`E-TRAIT-MISSING`], [트레이트의 op 하나가 없다], [#chref("traits")],
  [`E-TRAIT-SIG`], [서명에 `fn`·`proc` 을 적었거나 매개변수 수가 다르다], [#chref("traits")],
  [`E-TYPE-ARRAY`], [`array` 의 길이를 타입 뒤에 적었다], [#chref("slices")],
  [`E-TYPE-BITCAST`], [`bit_cast` 의 목표가 모든 비트열이 값인 타입이 아니다], [#chref("fixed-memory")],
  [`E-TYPE-COND`], [조건 자리에 참거짓이 아닌 값이 왔다], [#chref("numbers")],
  [`E-TYPE-DECL`], [타입 선언에 `be` 를 끼웠다], [#chref("named-types")],
  [`E-TYPE-INSTANCE`], [같은 제네릭의 서로 다른 인스턴스를 섞었다], [#chref("lib-alloc")],
  [`E-TYPE-MUT`], [`mut` 이 아닌 슬라이스의 원소에 쓴다], [#chref("slices")],
  [`E-TYPE-NOMINAL`], [표현이 같아도 이름이 다른 타입을 섞었다], [#chref("named-types")],
  [`E-TYPE-REF`], [읽기 참조로 쓴다], [#chref("references")],
  [`E-TYPE-SIGN`], [값을 지키는 넓히기가 없는 부호 섞기다], [#chref("numbers"), #chref("proofs-numbers")],
  [`E-TYPE-WIDTH`], [값이 선언된 타입에 들어가지 않는다], [#chref("surface")],
  [`E-VISIBILITY`], [다른 모듈의 감춘 이름에 닿는다], [#chref("modules")],
  [`E-VOCAB-REMOVED`], [없앤 낱말이나 철자다], [#chref("surface")],
  [`W-EFFECT-OVER`], [선언만 하고 내지 않는 효과다(경고)], [#chref("effects")],
  [`W-USE-EXTERNAL`], [번역 단위에 없는 모듈을 들여온다(경고)], [#chref("lib-map")],
)

== 실행 중에 멈출 때

#dtable(
  columns: 3,
  id: "a2-runtime",
  caption: [실행 중의 진단],
  [*코드*], [*뜻*], [*보이는 곳*],
  [`E-VM-OVERFLOW`], [정수가 선언된 폭에서 넘쳤다], [#chref("numbers")],
  [`E-VM-DIV0`], [0 으로 나누었다], [#chref("numbers")],
  [`E-VM-CAST`], [좁히기·`cast` 의 값이 목표 타입에 들어가지 않는다], [#chref("numbers")],
  [`E-VM-SHIFT`], [옮기는 칸 수가 폭 이상이다], [#chref("numbers")],
  [`E-VM-BOUNDS`], [색인이 범위 밖이다], [#chref("slices")],
  [`E-VM-NONE`], [없는 값을 꺼냈다], [#chref("option-result")],
  [`E-VM-CONTRACT`], [계약(`requires`·`ensures`·`errors`·범위)이 깨졌다], [#chref("contracts")],
  [`E-VM-PANIC`], [`panic` 을 불렀다], [#chref("control")],
  [`E-VM-ANALYSIS`], [지운 검사의 자리가 실제로 범위 밖이다(컴파일러 결함)], [#chref("proofs-numbers")],
  [`E-TEST-FAIL`], [시험의 `expect` 가 거짓이다], [#chref("build-test")],
)
