#import "../lib.typ": *

#clause("B", "부록 B — 진단 목록 (Annex B: Diagnostics)")[

  #para("1")[
    이 부록은 처리기가 낼 수 있는 진단 식별자를 모은다. 식별자는 안정하며,
    한 번 정해진 뜻은 바뀌지 아니한다(#cref("5.4")).
  ]

  #note[
    이 목록은 **생성된 것**이다. 사람이 손으로 고치지 아니한다 — 손으로 적은 목록은
    언어가 자라면 곧 낡기 때문이다. 목록이 실제 처리기와 어긋나면 검사기가 실패한다.
  ]

  #sub("B.1", "실행 중 트랩 (E-VM-…)")[
    #para("1")[프로그램이 도는 중에 조건이 깨져 즉시 멈춘 것. 모두 50 가지다.]
    #shape("실행 중 트랩 식별자", "E-VM-ALIGN  E-VM-ANALYSIS  E-VM-ARITY
E-VM-ASM  E-VM-AWAIT  E-VM-BOUNDS
E-VM-BOXPOOL  E-VM-BSETPOOL  E-VM-BUDGET
E-VM-CAST  E-VM-CHAIN-LIMIT  E-VM-CHAN
E-VM-CHAN-EMPTY  E-VM-CHAN-FULL  E-VM-CONTRACT
E-VM-CSTR  E-VM-DANGLING  E-VM-DEADLOCK
E-VM-DEPTH  E-VM-DIV0  E-VM-ERR
E-VM-EXCL  E-VM-EXTERN  E-VM-FD
E-VM-FHANDLE  E-VM-FIELD  E-VM-FILEPOOL
E-VM-FMODE  E-VM-FWHENCE  E-VM-MAILBOX-FULL
E-VM-MBOX  E-VM-MMIO  E-VM-NONE
E-VM-OOM  E-VM-OVERFLOW  E-VM-PANIC
E-VM-REACTOR  E-VM-READONLY  E-VM-RECPOOL
E-VM-RESERVE  E-VM-SCHED-LOOP  E-VM-SHANDLE
E-VM-SHIFT  E-VM-SOCKPOOL  E-VM-STACK
E-VM-STKPOOL  E-VM-TYPE  E-VM-UNDEF
E-VM-UNSUP  E-VM-VIEW")
  ]

  #sub("B.2", "경고 (W-…)")[
    #para("1")[번역은 되지만 저자가 봐야 하는 것. 모두 15 가지다.]
    #shape("경고 식별자", "W-CBE-SLOW  W-COL0  W-CONFIG-DEPENDS
W-CONTRACT-IGNORED  W-EFFECT-OVER  W-ERRORS-UNRAISED
W-EXPORT-HIDDEN  W-EXPORT-NOSYM  W-NOT-YET
W-PAR-OK  W-RESULT-DISCARD  W-RFC-PENDING
W-TEST-NOT-RUN  W-UNBOUND  W-USE-EXTERNAL")
  ]

  #sub("B.3", "번역 잘못 (E-…)")[
    #para("1")[적합하지 않은 프로그램이라 번역이 성공하지 않는 것. 모두 305 가지다.]
    #shape("번역 잘못 식별자", "E-ABI-TARGET-ALIGN  E-ABSORB-IMPURE  E-ABSORB-NOCONTRACT
E-ABSORB-NOREF  E-ABSORB-NOWHY  E-ABSORB-PLACE
E-ABSORB-SCOPE  E-ACCESS-MODE  E-ACTOR-FAILURE
E-ACTOR-FIELD  E-ACTOR-MAILBOX  E-ACTOR-STATE-REF
E-ACTOR-UNINIT  E-ALLOC-AMBIGUOUS  E-ALLOC-CAPACITY-MARK
E-ALLOC-NESTED  E-ALLOC-NOCAP  E-ALLOC-NOROOT
E-ALLOC-NOSOURCE  E-ALLOC-OUTLIVES  E-ALLOC-SHARED
E-ALLOC-TASK  E-ALLOC-USING-UNUSED  E-ASM-BIND
E-ASM-BODY  E-ASM-NOCAP  E-ASM-NOEFFECT
E-ASM-NOUNSAFE  E-ASM-OPERAND  E-ASM-OPTLIE
E-ASM-TARGET  E-ASM-TARGET-UNKNOWN  E-ASM-UNBOUND
E-ASM-UNUSED  E-ATOMIC-NOCAP  E-ATOMIC-ORDER
E-BITOP-TYPE  E-BLOCK-NOHEAD  E-BLOCK-UNCLOSED
E-BORROW-ESCAPE  E-BORROW-EXCL  E-BORROW-FIELD
E-BOUND-UNSAT  E-BRAND-REUSED  E-BUILD-MODE
E-BUILD-TIER  E-BUILTIN-BARE  E-BUILTIN-NAME
E-CAP-FORGE  E-CAP-KIND  E-CAP-LOCAL
E-CAP-MISSING  E-CAP-NOHOST  E-CFG-UNKNOWN-PROP
E-CHAN-UNBOUNDED  E-CHAR  E-CHAR-EMPTY
E-CHAR-NEWLINE  E-CHAR-UNTERM  E-CHAR-WIDTH
E-CLAUSE-ORDER  E-COLLECT-FULL  E-COMPTIME-ARG
E-COMPTIME-NONCONST  E-CONC-ALONE  E-CONC-DEADLOCK
E-CONFIG-DEPENDS  E-CONFIG-TYPE  E-CONFIG-UNDEF
E-CONST-NOTCOMPTIME  E-CONTRACT-DEAD  E-CONTRACT-IMPOSSIBLE
E-CONTRACT-MODE  E-CONTRACT-UNDEF  E-CONTRACT-UNSAT
E-DOT-DOUBLE  E-DOT-MISSING  E-DOT-STRAY
E-EFFECT  E-EFFECT-CALC  E-EFFECT-DUP
E-EFFECT-NO-CAP  E-EFFECT-NONE-MIX  E-EFFECT-PURITY
E-EFFECT-REDUNDANT  E-EFFECT-UNDEF  E-ENS-UNDEF
E-ENS-UNSUP  E-ENTRY-CAP  E-ENTRY-OUTPUT
E-ENTRY-PARAMS  E-ENUM-ARITY  E-ENUM-DOT
E-ENUM-FIELD  E-ENUM-INFINITE  E-ENUM-NOFIELD
E-ENUM-NOVARIANT  E-ENUM-PAYLOAD  E-ENUM-UNCHECKED
E-ENUM-VARIANT  E-ERR-UNDECLARED  E-ERR-UNDEF
E-ERRORS-STATE  E-ESCAPE  E-EXCL
E-EXCL-INPLACE  E-EXCL-MOVED  E-EXPECT-PLACE
E-EXPR-APP  E-EXPR-CHAIN  E-EXPR-UNARY
E-FFI-BODY  E-FFI-CAPKIND  E-FFI-LINK
E-FFI-NOCAP  E-FFI-NOEFFECT  E-FFI-NOUNSAFE
E-FFI-TYPE  E-FIELD-FORM  E-FIELD-GLUED
E-FIELD-MARK  E-FLOAT-NOFLOAT  E-FN-CAP
E-FN-NOTEXPORT  E-FN-UNDEF  E-FN-VALUE
E-FOLD-OP  E-FOLD-ORDER  E-FORM-UNEXPECTED
E-GROUP-UNCLOSED  E-GUARD-FALLTHROUGH  E-HEAD-NOT-AN-OP
E-HEAP-NOCAP  E-HEAP-NOHOST  E-HEREDOC-TERM
E-HEREDOC-UNTERM  E-IF-VALUE  E-IMMUTABLE
E-INPLACE-FORM  E-INPLACE-UNPROVEN  E-INVALIDATES-FORM
E-IR-ARITY  E-IR-EXTRA  E-IR-LIMIT
E-IR-LOCALS  E-IR-UNDEF  E-IR-UNSUP
E-ISR-CALLED  E-ISR-EFFECT  E-ISR-OUTPUT
E-ISR-PARAMS  E-LET-NOVALUE  E-LEX-UTF8
E-LIT-RANGE  E-LOCK-NOTYET  E-LOOP-OUTSIDE
E-MAP-ELEM  E-MAP-SINK  E-MATCH-ARITY
E-MATCH-INEXHAUSTIVE  E-MATCH-ORBIND  E-MATCH-REDUNDANT
E-MATCH-UNDEF  E-METHOD-RECV  E-METHOD-UNDEF
E-MMIO-BASE  E-MMIO-BYVALUE  E-MMIO-FIELD
E-MMIO-NOBASE  E-MMIO-NOCAP  E-MMIO-NOEFFECT
E-MMIO-NOHOST  E-MMIO-PERM  E-MMIO-PLAIN
E-MONO-FIXPOINT  E-MONO-NOTYPE  E-MREF-SLICE
E-NAME-ASCII  E-NAME-BUILTIN  E-NAME-COLLISION
E-NAME-DOTTED  E-NAME-DUP  E-NAME-KEYWORD
E-NAME-QUALIFIER  E-NAME-SCOPE  E-NAME-SHADOW
E-NAME-VENDOR-RESERVED  E-NAME-WILDCARD  E-NEST-DEPTH
E-NOTE-UNTERM  E-NUM-EMPTY  E-NUM-SEP
E-NUM-SUFFIX  E-OPT-DEPENDS  E-OPT-TYPE
E-OPT-UNUSED  E-OWN-BARE  E-OWN-INCOMPLETE
E-OWN-JOIN  E-OWN-MOVED  E-OWN-PARTIAL
E-PAR-ASSOC  E-PAR-CARRY  E-PAR-FLOAT
E-PAR-IDENTITY  E-PAR-NOLOOP  E-PAR-READ
E-PAR-WRITE  E-PAREN-ESCAPE  E-PAREN-STRAY
E-PAREN-UNCLOSED  E-PARSE-LIMIT  E-PIPE-NO-TERMINAL
E-PIPE-PRED  E-PIPE-STAGE  E-PKG-DUP
E-PKG-FORM  E-PKG-KEY  E-PKG-NONAME
E-PKG-NOVERSION  E-PKG-VERSION  E-PROFILE-LEVEL
E-PROFILE-UNKNOWN  E-REGION-ESCAPE  E-REGION-KIND
E-REGION-UNDEF  E-REQ-UNDEF  E-REQ-UNSUP
E-RESERVE-NOCAP  E-RESERVE-NOEFFECT  E-RESERVE-NOHOST
E-RETURN-PARTIAL  E-SHIFT-RANGE  E-SPAWN-SCOPE
E-STMT-ELSE  E-STMT-NODO  E-STR-ESCAPE
E-STR-NEWLINE  E-STR-PREFIX  E-STR-UNTERM
E-STRUCT-CYCLE  E-STRUCT-REF-UNMANAGED  E-TARGET-INTRIN
E-TARGET-ISET  E-TARGET-LEAF  E-TEST-FAIL
E-TIER-EFFECT  E-TOPLEVEL  E-TRAIT-EFFECT
E-TRAIT-MISSING  E-TRAIT-RECV  E-TRAIT-SIG
E-TRAIT-UNDEF  E-TRY-NORESULT  E-TYPE-ALIGN
E-TYPE-ARG  E-TYPE-ARGMUT  E-TYPE-ARRAY
E-TYPE-BITCAST  E-TYPE-COLLECT  E-TYPE-COND
E-TYPE-CYCLE  E-TYPE-CYCLE-LIMIT  E-TYPE-DECL
E-TYPE-FIELD  E-TYPE-INSTANCE  E-TYPE-ITER
E-TYPE-KIND  E-TYPE-LANES  E-TYPE-LAYOUT
E-TYPE-LET  E-TYPE-LIMIT  E-TYPE-LOGICAL
E-TYPE-MASK  E-TYPE-MIX  E-TYPE-MUT
E-TYPE-NOMINAL  E-TYPE-RANGE  E-TYPE-REF
E-TYPE-REFVAL  E-TYPE-RETMUT  E-TYPE-RETURN
E-TYPE-SET  E-TYPE-SIGN  E-TYPE-STRUCT
E-TYPE-TRY  E-TYPE-UNDEF  E-TYPE-VAR
E-TYPE-WIDTH  E-TYPE-WRAP  E-UNSAFE-UNDECLARED
E-UNSAFE-UNUSED  E-UPTR-TYPE  E-USE-ALIASED
E-USING-DUP  E-USING-FORM  E-USING-UNRESOLVED
E-VEC-QUAL  E-VEC-SPLAT  E-VIEW-INVALIDATED
E-VISIBILITY  E-VOCAB-REMOVED  E-WIDEN-KIND
E-WIDEN-NARROW  E-WIDEN-SIGN")
  ]

]
