#import "../lib.typ": *

#clause("C", "부록 C — 용어 색인 (Annex C: Index of terms)")[

  #para("1")[
    이 문서에 나오는 용어를 가나다 차례로 모은다. 각 용어의 뜻은 적힌 조항에 있다.
  ]

  #note[
    이 색인은 #strong[생성된 것];이다. 사람이 손으로 고치지 아니한다.
  ]

  #tbl("용어 색인")[
    #table(columns: (auto, auto, auto), stroke: 0.5pt + rgb("#bbb"), inset: 5pt,
      [*용어*], [*영어*], [*조항*],
      [BOM], [byte order mark], [#cref("3.7")],
      [access], [access declaration], [#cref("6.4.3")],
      [effects], [effect declaration], [#cref("6.4.3")],
      [ensures], [postcondition], [#cref("6.4.3")],
      [errors], [error condition], [#cref("6.4.3")],
      [fn], [pure op], [#cref("6.4.1")],
      [mut_ref], [exclusive reference], [#cref("8.4")],
      [op], [op], [#cref("3.1")],
      [proc], [effectful op], [#cref("6.4.1")],
      [ref], [shared reference], [#cref("8.4")],
      [requires], [precondition], [#cref("6.4.3")],
      [tests], [examples], [#cref("6.4.3")],
      [가비지 컬렉터], [garbage collector], [#cref("2.2")],
      [값], [value], [#cref("3.2")],
      [개행], [newline], [#cref("3.7")],
      [검사], [check], [#cref("3.3")],
      [계약], [contract], [#cref("1.3")],
      [구문], [syntax], [#cref("1.1")],
      [구문 문법], [syntactic grammar], [#cref("1.5")],
      [구현 정의], [implementation-defined], [#cref("4.3")],
      [권한], [capability], [#cref("3.4")],
      [규범], [normative], [#cref("1.4")],
      [기계], [target], [#cref("5.6")],
      [기본 연산], [core op], [#cref("3.8")],
      [낱말], [keyword], [#cref("3.7")],
      [넓히기], [widening], [#cref("3.8")],
      [능력], [capability], [#cref("5.3")],
      [단락 평가], [short-circuit], [#cref("3.8")],
      [단언], [assertion], [#cref("6.4.13")],
      [닫개], [closer], [#cref("3.7")],
      [덫 표현], [trap representation], [#cref("3.2")],
      [덫 표현], [trap
      representation], [#cref("8.7.1")],
      [등급], [grade], [#cref("6.4.9")],
      [라이브러리 모듈], [library module], [#cref("3.9")],
      [로우엔트], [Lowent], [#cref("1.1")],
      [로컬 op], [local op], [#cref("3.9")],
      [리터럴], [literal], [#cref("3.2")],
      [리프], [leaf], [#cref("9.3")],
      [모듈], [module], [#cref("3.1")],
      [모호], [open issue], [#cref("4.3")],
      [목적지], [destination], [#cref("3.9")],
      [문맥], [context], [#cref("3.9")],
      [문자 리터럴], [character literal], [#cref("3.2")],
      [문자열 리터럴], [string literal], [#cref("3.2")],
      [문장], [statement], [#cref("3.8")],
      [미정의 동작], [undefined behaviour], [#cref("3.3")],
      [번역], [translation], [#cref("3.6")],
      [번역 단위], [translation unit], [#cref("5.1")],
      [번역 환경], [translation environment], [#cref("3.9")],
      [부동소수 리터럴], [floating-point literal], [#cref("3.2")],
      [빌드 모드], [build mode], [#cref("3.3")],
      [빌트인 연산], [builtin op], [#cref("3.8")],
      [사전 조건], [precondition], [#cref("3.3")],
      [사후 조건], [postcondition], [#cref("3.3")],
      [상표], [brand], [#cref("3.2")],
      [생성 규칙], [production], [#cref("1.5")],
      [선언], [declaration], [#cref("3.1")],
      [섬], [island], [#cref("3.7")],
      [소유], [ownership], [#cref("3.5")],
      [순수], [pure], [#cref("3.4")],
      [스테이지], [stage], [#cref("3.9")],
      [슬라이스], [slice], [#cref("3.2")],
      [시작점], [entry point], [#cref("3.9")],
      [시험 블록], [test block], [#cref("6.4.13")],
      [식], [expression], [#cref("3.8")],
      [신뢰 경계], [trust boundary], [#cref("3.3")],
      [실행 환경], [execution environment], [#cref("3.9")],
      [안전한 부분집합], [safe subset], [#cref("3.3")],
      [액터], [actor], [#cref("3.8")],
      [어휘 문법], [lexical grammar], [#cref("1.5")],
      [얼로케이터], [allocator], [#cref("8.13")],
      [열거], [enum], [#cref("3.2")],
      [영역], [region], [#cref("3.5")],
      [옥텟], [octet], [#cref("3.9")],
      [완결], [completion], [#cref("8.5")],
      [의미 규칙], [semantic rules], [#cref("1.1")],
      [의미 엔트로피], [semantic entropy], [#cref("1.3")],
      [이름], [identifier], [#cref("3.7")],
      [이스케이프], [escape], [#cref("3.2")],
      [임시값], [temporary], [#cref("3.9")],
      [자리], [place], [#cref("3.9")],
      [자유 선택], [free choice], [#cref("1.3")],
      [적합성], [conformance], [#cref("1.1")],
      [적합한 처리기], [conforming processor], [#cref("3.6")],
      [적합한 프로그램], [conforming program], [#cref("3.6")],
      [전위 표기], [prefix notation], [#cref("3.7")],
      [접두사], [prefix], [#cref("3.2")],
      [정의], [definition], [#cref("3.1")],
      [제약], [constraints], [#cref("1.1")],
      [좁히기], [narrowing], [#cref("3.8")],
      [종결자], [terminal], [#cref("3.9")],
      [종료 상태], [exit status], [#cref("3.9")],
      [주석], [comment], [#cref("3.7")],
      [중위 표기], [infix notation], [#cref("3.7")],
      [진단], [diagnostic], [#cref("3.6")],
      [참고], [informative], [#cref("1.4")],
      [참조], [reference], [#cref("3.5")],
      [채널], [channel], [#cref("10.6")],
      [처리기], [processor], [#cref("1.1")],
      [최적화], [optimisation], [#cref("3.9")],
      [타입], [type], [#cref("3.2")],
      [탈출], [escape], [#cref("3.5")],
      [텍스트 리터럴], [text literal], [#cref("3.2")],
      [토큰], [token], [#cref("3.7")],
      [투스 컴플리먼트], [two's complement], [#cref("3.9")],
      [트랩], [trap], [#cref("3.3")],
      [트레이트], [trait], [#cref("3.8")],
      [폭], [width], [#cref("3.2")],
      [폼], [form], [#cref("3.7")],
      [표지], [marker], [#cref("6.2.15")],
      [표현], [representation], [#cref("1.1")],
      [프로그램], [program], [#cref("3.1")],
      [프리스탠딩], [freestanding], [#cref("2.2")],
      [한정], [qualification], [#cref("3.9")],
      [해제], [release], [#cref("8.5")],
      [호스티드], [hosted], [#cref("5.1")],
      [효과], [effect], [#cref("3.4")],
    )
  ]
]
