#import "../../book/lib.typ": *

= Appendix B --- Diagnostics index

Only the diagnostics that this book's examples actually trigger are listed. A code keeps its meaning across releases; the compiler explains the details and the repair at the site.

== At translation time

#dtable(
  columns: 3,
  id: "a2-static",
  caption: [Diagnostics shown by the examples],
  [*Code*], [*Meaning*], [*Shown in*],
  [`E-ALLOC-NESTED`], [allocated from an outer source while an inner region of the same root is open], [#chref("regions")],
  [`E-ALLOC-NOCAP`], [declares `alloc` but receives no allocation capability], [#chref("capabilities")],
  [`E-ASM-UNBOUND`], [the assembly template names an undeclared operand], [#chref("hardware")],
  [`E-ATOMIC-NOCAP`], [declares `atomic` but receives no `cap atomic`], [#chref("parallel-atomic")],
  [`E-ATOMIC-ORDER`], [a memory ordering that has no meaning for that atomic operation], [#chref("parallel-atomic")],
  [`E-BOUND-UNSAT`], [the type argument does not satisfy the required trait], [#chref("generics")],
  [`E-CAP-FORGE`], [spawns an actor holding a capability without holding that capability], [#chref("fixed-memory")],
  [`E-CAP-KIND`], [a capability of the wrong kind was handed over], [#chref("capabilities")],
  [`E-CAP-MISSING`], [a capability-requiring builtin was not given its capability as the first operand], [#chref("capabilities")],
  [`E-CLAUSE-ORDER`], [the clauses of an op header are out of the fixed order], [#chref("first-program")],
  [`E-COMPTIME-ARG`], [a run-time value in a `comptime` position], [#chref("generics")],
  [`E-CONC-ALONE`], [a task group spawns one task that waits for a peer], [#chref("tasks-channels")],
  [`E-CONC-DEADLOCK`], [every task in the group receives and none sends], [#chref("tasks-channels")],
  [`E-CONTRACT-DEAD`], [declares an error that `requires` already excludes], [#chref("contracts")],
  [`E-CONTRACT-IMPOSSIBLE`], [a call with constant arguments breaks the callee's `requires`], [#chref("contracts"), #chref("lib-alloc")],
  [`E-EFFECT`], [performs an effect its `effects` clause does not declare], [#chref("effects"), #chref("tasks-channels")],
  [`E-EFFECT-CALC`], [a pure `fn` performs an effect], [#chref("intro"), #chref("ops")],
  [`E-EFFECT-DUP`], [the same atom twice in an `effects` clause], [#chref("effects")],
  [`E-EFFECT-NO-CAP`], [declares `io` (or similar) without a capability that authorises it], [#chref("capabilities")],
  [`E-EFFECT-NONE-MIX`], [`none` written together with a real effect], [#chref("effects")],
  [`E-EFFECT-PURITY`], [a `fn` writes state visible to its caller or actor], [#chref("ops"), #chref("actors")],
  [`E-EFFECT-REDUNDANT`], [`effects none` written on a `fn`], [#chref("ops")],
  [`E-EFFECT-UNDEF`], [an effect word outside the closed vocabulary], [#chref("effects")],
  [`E-ENTRY-PARAMS`], [the entry point takes a non-capability input], [#chref("capabilities")],
  [`E-ENUM-DOT`], [an enum variant not closed with `.`], [#chref("structs-enums")],
  [`E-ENUM-INFINITE`], [a variant embeds its own type by value], [#chref("structs-enums")],
  [`E-ERR-UNDECLARED`], [returns an error not in its `errors` clause], [#chref("option-result")],
  [`E-ESCAPE`], [a reference to a local escapes the op], [#chref("references")],
  [`E-EXCL`], [overlapping borrows or owner access to the same value], [#chref("references"), #chref("proofs-ownership")],
  [`E-EXPR-APP`], [a call inside an `expr` island is not parenthesised], [#chref("expr")],
  [`E-EXPR-CHAIN`], [comparisons chained in an `expr` island], [#chref("surface")],
  [`E-EXPR-UNARY`], [a unary operator in an `expr` island], [#chref("expr")],
  [`E-FFI-NOCAP`], [calls C without receiving `cap c`], [#chref("ffi")],
  [`E-FFI-NOUNSAFE`], [calls C without the `unsafe` mark], [#chref("ffi")],
  [`E-FFI-TYPE`], [a type the C ABI cannot express crosses the boundary], [#chref("ffi")],
  [`E-GROUP-UNCLOSED`], [an unclosed parenthesis], [#chref("surface")],
  [`E-GUARD-FALLTHROUGH`], [the `else` of a `guard` does not leave], [#chref("control")],
  [`E-HEAP-NOHOST`], [asks for the growing root on a freestanding target], [#chref("regions")],
  [`E-IF-VALUE`], [`if` used as a value], [#chref("locals")],
  [`E-IMMUTABLE`], [`set` on a name bound with `let`], [#chref("locals")],
  [`E-ISR-CALLED`], [an interrupt handler called from code], [#chref("hardware")],
  [`E-LET-NOVALUE`], [nothing after `be`], [#chref("locals")],
  [`E-MATCH-INEXHAUSTIVE`], [a `match` does not cover every case], [#chref("control"), #chref("structs-enums")],
  [`E-METHOD-UNDEF`], [no op of that name is attached to the receiver's type], [#chref("traits")],
  [`E-MMIO-BYVALUE`], [an mmio register block taken by value], [#chref("hardware")],
  [`E-MMIO-PERM`], [writes a read-only register], [#chref("hardware")],
  [`E-MREF-SLICE`], [`mut ref slice` used], [#chref("references")],
  [`E-NAME-DUP`], [the same name declared twice in one module], [#chref("modules")],
  [`E-NAME-SHADOW`], [re-binds a live name (shadowing)], [#chref("surface"), #chref("locals")],
  [`E-OPT-UNUSED`], [a declared build option that no code reads], [#chref("build-test")],
  [`E-OWN-INCOMPLETE`], [a value that needs completion is dropped implicitly], [#chref("ownership"), #chref("io-files"), #chref("lib-io-net")],
  [`E-OWN-JOIN`], [ownership state differs between branches], [#chref("ownership")],
  [`E-OWN-MOVED`], [uses a value after it was moved], [#chref("ownership"), #chref("actors"), #chref("lib-alloc")],
  [`E-PAR-ASSOC`], [the reduction operator is not associative], [#chref("parallel-atomic")],
  [`E-PAR-CARRY`], [a split loop writes a local that lives across iterations], [#chref("parallel-atomic")],
  [`E-PAR-READ`], [a split loop reads another iteration's element], [#chref("parallel-atomic")],
  [`E-PIPE-NO-TERMINAL`], [a stage after the terminal], [#chref("pipe")],
  [`E-PIPE-STAGE`], [a word that is not a `pipe` stage], [#chref("pipe")],
  [`E-PROFILE-LEVEL`], [uses concurrency the build profile does not provide], [#chref("actors")],
  [`E-REGION-ESCAPE`], [carries region bytes out of the region], [#chref("regions")],
  [`E-REGION-KIND`], [a region kind outside the closed eight], [#chref("regions")],
  [`E-RETURN-PARTIAL`], [some path does not return a value], [#chref("control")],
  [`E-SPAWN-SCOPE`], [spawns a task outside a `task_group`], [#chref("tasks-channels")],
  [`E-TIER-EFFECT`], [an effect the declared machine tier cannot carry], [#chref("hardware")],
  [`E-TRAIT-EFFECT`], [the implementing op has more effects than the signature], [#chref("traits")],
  [`E-TRAIT-MISSING`], [an op required by the trait is missing], [#chref("traits")],
  [`E-TRAIT-SIG`], [`fn`/`proc` in a signature, or a parameter-count mismatch], [#chref("traits")],
  [`E-TYPE-ARRAY`], [`array` length written after the type], [#chref("slices")],
  [`E-TYPE-BITCAST`], [`bit_cast` target is not a plain scalar], [#chref("fixed-memory")],
  [`E-TYPE-COND`], [a non-boolean in a condition], [#chref("numbers")],
  [`E-TYPE-DECL`], [`be` in a type declaration], [#chref("named-types")],
  [`E-TYPE-INSTANCE`], [mixes different instances of the same generic], [#chref("lib-alloc")],
  [`E-TYPE-MUT`], [writes an element of a non-`mut` slice], [#chref("slices")],
  [`E-TYPE-NOMINAL`], [mixes nominally distinct types], [#chref("named-types")],
  [`E-TYPE-REF`], [writes through a shared `ref`], [#chref("references")],
  [`E-TYPE-SIGN`], [mixes signs with no value-preserving widening], [#chref("numbers"), #chref("proofs-numbers")],
  [`E-TYPE-WIDTH`], [the value does not fit the declared type], [#chref("surface")],
  [`E-VISIBILITY`], [reaches a non-exported name of another module], [#chref("modules")],
  [`E-VOCAB-REMOVED`], [a removed word or spelling], [#chref("surface")],
  [`W-EFFECT-OVER`], [an effect declared but never performed (warning)], [#chref("effects")],
  [`W-USE-EXTERNAL`], [imports a module not in the compilation unit (warning)], [#chref("lib-map")],
)

== When execution stops

#dtable(
  columns: 3,
  id: "a2-runtime",
  caption: [Run-time diagnostics],
  [*Code*], [*Meaning*], [*Shown in*],
  [`E-VM-OVERFLOW`], [integer overflow at the declared width], [#chref("numbers")],
  [`E-VM-DIV0`], [division by zero], [#chref("numbers")],
  [`E-VM-CAST`], [a narrowing or `cast` value does not fit], [#chref("numbers")],
  [`E-VM-SHIFT`], [shift amount not smaller than the width], [#chref("numbers")],
  [`E-VM-BOUNDS`], [index out of bounds], [#chref("slices")],
  [`E-VM-NONE`], [took the value out of `none`], [#chref("option-result")],
  [`E-VM-CONTRACT`], [a contract was broken], [#chref("contracts")],
  [`E-VM-PANIC`], [the program called `panic`], [#chref("control")],
  [`E-VM-ANALYSIS`], [an eliminated check was actually needed (compiler bug)], [#chref("proofs-numbers")],
  [`E-TEST-FAIL`], [an `expect` in a test is false], [#chref("build-test")],
)
